[package]
name = "identity-sequencer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "crates/sequencer",
  "crates/tree_state",
  "crates/state_bridge",
  "crates/common"
]


[[bin]]
name = "identity-sequencer"
path = "bin/identity_sequencer_service.rs"

[[bin]]
name = "state-bridge-service"
path = "bin/state_bridge_service.rs"


[[bin]]
name = "tree-availability-service"
path = "bin/tree_availability_service.rs"

[dependencies]
chrono = "0.4.31"
clap = { version = "4.4.6", features = ["derive"] }
derive = "1.0.0"
ethers = { version = "2.0.10", features = ["openssl", "rustls", "ipc"] }
hex-literal = "0.4.1"
serde = "1.0.189"
state_bridge = {path = "crates/state_bridge"}
common = {path = "crates/common"}
tokio = { version = "1.33.0", features = ["full"] }
toml = "0.8.2"
eyre = "0.6.8"

