[package]
name = "identity-sequencer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "crates/sequencer",
  "crates/tree_state",
  "crates/state_bridge",
]


[[bin]]
name = "identity-sequencer"
path = "bin/identity_sequencer.rs"

[[bin]]
name = "state-bridge-service"
path = "bin/state_bridge_service.rs"


[[bin]]
name = "tree-availability-service"
path = "bin/tree_availability_service.rs"
[dependencies]

