
l1_rpc_endpoint = "http://your_rpc_endpoint.com"
l1_world_id = "0x00"
block_confirmations = 5


# Optimism
[[state_bridge]]
l1_state_bridge = ""
l2_world_id_address = ""
l2_rpc_endpoint = ""
relaying_period_seconds = 3600


# Polygon
[[state_bridge]]
l1_state_bridge = ""
l2_world_id_address = ""
l2_rpc_endpoint = ""
relaying_period_seconds = 3600


